service: product-service

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  profile: danila_loginov

  environment:
    DB_HOST: host
    DB_PORT: port
    DB_DATABASE: database
    DB_USER: user
    DB_PASSWORD: password

plugins:
  - serverless-plugin-webpack

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
