service: product-service

custom:
  # Variables not exposed to the application.
  snsTopicName: createProductTopic
  sqsQueueName: catalogItemsQueue

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  profile: danila_loginov

  environment:
    # Variables exposed to the application.
    SNS_TOPIC_ARN:
      Ref: SnsTopic

  iamRoleStatements:
    - Action:
        - sns:*
      Effect: Allow
      Resource:
        - Ref: SnsTopic
    - Action:
        - sqs:*
      Effect: Allow
      Resource:
        - !ImportValue ${self:custom.sqsQueueName}Arn

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-webpack

resources:
  Resources:
    # @see https://github.com/serverless/serverless/issues/3896
    # @see https://docs.aws.amazon.com/apigateway/latest/developerguide/supported-gateway-response-types.html
    UnauthorizedGatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
    AccessDeniedGatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: ACCESS_DENIED
        RestApiId:
          Ref: ApiGatewayRestApi
    Default4XXGatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    SnsSubscriptionSingle:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:SNS_SUBSCRIPTION_SINGLE_ENDPOINT}
        FilterPolicy:
          numOfProducts:
            - numeric:
                - "<"
                - 2
        Protocol: email
        TopicArn:
          Ref: SnsTopic
    SnsSubscriptionMultiple:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:SNS_SUBSCRIPTION_MULTIPLE_ENDPOINT}
        FilterPolicy:
          numOfProducts:
            - numeric:
                - ">="
                - 2
        Protocol: email
        TopicArn:
          Ref: SnsTopic
    SnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.snsTopicName}

functions:
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            !ImportValue ${self:custom.sqsQueueName}Arn
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
          authorizer: ${env:COGNITO_USER_POOL_ARN}
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
          authorizer: ${env:COGNITO_USER_POOL_ARN}
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          authorizer: ${env:COGNITO_USER_POOL_ARN}
          request:
            parameters:
              paths:
                id: true
