openapi: 3.0.3

info:
  title: nodejs-aws-be/authorization-service
  version: 0.0.0
  contact:
    name: Danila Loginov
    url: https://github.com/loginov-rocks/nodejs-aws-be

servers:
  - url: https://.execute-api.eu-central-1.amazonaws.com/dev/

components:

  schemas:

    HttpError:
      type: object
      properties:
        message:
          type: string
      required:
        - message

  responses:

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'
