service: authorization-service

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  profile: danila_loginov

  environment:
    # Variables exposed to the application.
    username: password

plugins:
  - serverless-plugin-webpack

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
    events:
      - http:
          path: token
          method: get
          cors: true
